### ISSUE TITLE
Conversion of notebooks of ML4Nets course

### ISSUE THREAD

**Issue by IngoScholtes** [pathpy/pathpyG#101]
To test whether the functionality needed for the ML4Nets course has been implemented in pathpyG, we should start converting the practice notebooks, which are [available here](https://gitlab.informatik.uni-wuerzburg.de/ml4nets_notebooks/2024_sose_ml4nets_notebooks). 

- [x] Week 01: Introduction to python and pathpyG [@IngoScholtes]
- [x] Week 02: Shortest paths, Components, Spectral Clustering [@IngoScholtes]
- [x] Week 03: Random Graphs and Molloy-Reed Model [@IngoScholtes]
- [x] Week 04: Stochastic Block Model [@chrisbloecker]
- [x] Week 05: Entropy and Huffman Coding [@chrisbloecker]
- [x] Week 06: Random Walks and InfoMap [@FranziskHeeg]
- [x] Week 07: Similarity Scores and Link Prediction [@IngoScholtes]
- [x] Week 08: Dimensionality Reduction and Laplacian Eigenmaps [@VincenzoPerri]
- [x] Week 09: Logistic Regression and Neural Networks [does not use pathpyG]
- [x] Week 10: DeepWalk and node2vec [@lisiq]
- [x] Week 11: Graph Neural Networks [@lisiq]

**Comment by lisiq** [comment]
Week 11 done
