### ISSUE TITLE
Code reference pages return 404 error

### ISSUE THREAD

**Issue by IngoScholtes** [pathpy/pathpyG#114]
This holds for all classes in the core module, e.g. [this on](https://www.pathpy.net/dev/reference/pathpyG/core/Graph/) as well as for the io and nn modules.

**Comment by M-Lampert** [comment]
Sorry, I am currently working on a fix for the version selector returning a 404 error. During that the documentation might have not been available for a few minutes. This might be because of this.

**Comment by IngoScholtes** [comment]
No need to be sorry and thanks for your great work!

**Comment by IngoScholtes** [comment]
As soon as I have completed the refactoring of the `PathData` class (and as soon as we have expanded the test coverage a bit more), we can release a first `stable` version. After this refactoring is done, I do not expect substantial API changes.
