### ISSUE TITLE
Extend `append_DAG` to work with nodes appearing at multiple points in time

### ISSUE THREAD

**Issue by M-Lampert** [pathpy/pathpyG#165]
@VincenzoPerri raised the issue that we currently cannot add a DAG that should contain the same node at multiple time stamps. We already fixed this issue for `append_walk` by reindexing all nodes contained in the walk. It is not as trivial for DAGs since a node can have multiple incoming and outgoing edges so we cannot use a new index for each occurrence in the edge index.
One solution could be that we use the combination of node index and time stamp to reindex the nodes.

**Comment by IngoScholtes** [comment]
Since we have removed the support for DAGs (as we now directly calculate Multi-Oder Models from a Temporal Graph) this issue can be closed.
