### ISSUE TITLE
Bug in plot function for temporal networks 

### ISSUE THREAD

**Issue by FranziskHeeg** [pathpy/pathpyG#224]
Plot function for temporal networks is not working, when network is created by `pp.TemporalGraph.from_edge_list()` with timestamps and nodes as integers.

This works: 
<img width="471" alt="Screenshot 2024-11-14 at 11 55 10" src="https://github.com/user-attachments/assets/9ba755f5-4c28-4a1f-91cc-5616a3c2de6f">

This does not work: 
<img width="442" alt="Screenshot 2024-11-14 at 11 53 49" src="https://github.com/user-attachments/assets/65c65458-133b-4ab7-842d-f34b463d06eb">

This works again:
<img width="463" alt="Screenshot 2024-11-14 at 11 54 20" src="https://github.com/user-attachments/assets/ddc91784-10b1-4522-a2d0-cae2fc42eb8b">

**Comment by hackl** [comment]
Seems `json` cannot encode `numpy` values. See https://stackoverflow.com/questions/50916422/python-typeerror-object-of-type-int64-is-not-json-serializable

Solution:

```python
import json
import numpy as np

class NpEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return super(NpEncoder, self).default(obj)

# Your codes .... 
json.dumps(data, cls=NpEncoder)
```
