### ISSUE TITLE
notebook crashing when plotting weighted graph

### ISSUE THREAD

**Issue by IngoScholtes** [pathpy/pathpyG#74]
The plots of weighted (higher-order) graphs in the dbgnn tutorial currently leads to the notebook crashing. The resulting HTML output has a lot of NaN errors, which are likely due to layout algorithm.

Minimal example to reproduce the issue: 

```
import pathpyG as pp
pp.config['torch']['device'] = 'cpu'

# read paths
paths = pp.PathData.from_csv('../data/temporal_clusters.ngram')

ho = pp.HigherOrderGraph(paths, order=1)

pp.plot(ho, filename='test.html')
```

The resulting HTML file does not render and the console logs a large number of errors.

**Comment by hackl** [comment]
I will have a look.

**Comment by hackl** [comment]
To overcome that, the weights clutter the plot too much; the force size of d3js can be changed with the option `charge_force`

```python
pp.plot(ho, filename="test.html", charge_force=-8000)
```
